[project]
name = "task-management-service"
version = "0.1.0"
description = "Сервис управления задачами"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.0",
    "asyncpg>=0.30.0",
    "fastapi[all]>=0.120.1",
    "sqlalchemy[asyncio]>=2.0.44",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "mypy>=1.18.2",
    "ruff>=0.14.2",
]

# mypy settings

[tool.mypy]
strict = true
plugins = [
    "pydantic.mypy",
]
