management-service:
  logging:
    log_level_name: INFO

  postgres:
    host: localhost
    port: 5432
    db: postgres
    user: postgres
    password: ""

  rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
    queue_name: task_queue
    exchange_name: task_exchange
